=== AlexandraRyzvanovich/greanHouse/src/test/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element name="student"
                         type="tns:Flower"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Flower">
        <sequence>
            <element name="name" type="string" />
            <element name="soil" type="tns:Soil" />
            <element name="color" type="tns:Color" />
            <element name="growingTips" type="string" />
            <element name="multiplying" type="tns:Multiplying" />
        </sequence>
        <attribute name="login" type="tns:ID" use="required" />
    </complexType>
    <simpleType name="ID">
        <restriction base="ID">
        <pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}"/>
        </restriction>
    </simpleType>
    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="pozolic"/>
            <enumeration value="sod podzolic"/>
            <enumeration value="ground"/>
        </restriction>
    </simpleType>
    <simpleType name="Color">
        <restriction base="string">
        <enumeration value="white"/>
        <enumeration value="red"/>
        <enumeration value="yellow"/>
        <enumeration value="pink"/>
        </restriction>
    </simpleType>
    <simpleType name="Multiplying">
        <restriction base="string">
        <enumeration value="leaves"></enumeration>
        <enumeration value="cuttage"></enumeration>
        <enumeration value="seads"></enumeration>
        </restriction>
    </simpleType>
    <complexType name="Rose">
        <complexContent>
            <extension base="tns:Flower">
                <attribute name="blossomTime" type="string" use="optional" default="summer"/>
                <attribute name="petalQuantity" type="int" use="optional" default="7"/>
                <attribute name="budType" type="string" use="optional"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="HybridRose">
        <complexContent>
            <extension base="tns:Rose">
                <attribute name="hybridRoseSubSort" use="required" default="large flowered">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="large flowered"/>
                            <enumeration value="cluster flowered"/>
                            <enumeration value="hybrid tea rose"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="yearOfSelection" type="int" default="1999"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="GardenRose">
        <complexContent>
            <extension base="tns:Rose">
                <attribute name="gardenRoseSort" use="required" default="rose de rescht">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="rose de rescht"/>
                            <enumeration value="fransis lubrel"/>
                            <enumeration value="lady banky"/>
                            <enumeration value="green rose"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="bushType" use="optional" default="single">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="single"/>
                            <enumeration value="climbing"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="WildRose">
        <complexContent>
            <extension base="tns:Rose">
                <attribute name="wildRoseSort" use="required" default="rugosa rose">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="rugosa rose"/>
                            <enumeration value="bracteata rose"/>
                            <enumeration value="foliolosa rose"/>
                            <enumeration value="woolsii rose"/>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="fruitsForm" type="string" use="required"/>
            </extension>
        </complexContent>
    </complexType>
    <element name="flower" type="tns:Flower" abstract="true"></element>
    <element name="rose" type="tns:Rose" substitutionGroup="tns:flower"></element>
    <element name="hybridRose" type="tns:HybridRose" substitutionGroup="tns:rose"></element>
    <element name="gardenRose" type="tns:GardenRose" substitutionGroup="tns:rose"></element>
    <element name="wildRose" type="tns:WildRose" substitutionGroup="tns:rose"></element>

</schema>

=== AlexandraRyzvanovich/greanHouse/src/test/resources/flowers.xml
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:ns="http://www.example.com/flowers"
          xsi:schemaLocation="http://www.epam.com/test/flowers flowers.xsd">
    <Hybridrose id = '1'>
        <name> Rose</name>
        <soil>Ground soil</soil>
        <color>White</color>
        <growingTips>Grow in warm climate and cut once a year.</growingTips>
        <multiplying>Seeds multiplying</multiplying>
        <blossomTime>all year round</blossomTime>
        <petalQuantity>10</petalQuantity>
        <budType>From small to huge with central bud</budType>
        <gardenRoseSort>Green rose</gardenRoseSort>
        <bushType>Climbing bush</bushType>
    </Hybridrose>

</flowers>
